Fix idle connection disposal
ReactiveMongo/ReactiveMongo pull request #1037
Opened 2021-05-10 19:26 UTC by jaceksokol

# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://github.com/ReactiveMongo/ReactiveMongo/blob/master/CONTRIBUTING.md#reactivemongo-developer--contributor-guidelines)?
* [ ] Have you added tests for any changed functionality?

## Fixes

Fixes an issue described in: https://groups.google.com/g/reactivemongo/c/3Kb-tpAcO6Y

## Purpose

Fixes idle connection disposal.

## Background Context

The `IdleStateHandler` should be set as first in the netty's pipeline (according to the documentation). This was not true if SSL was enabled.

## References

* Described issue with code to reproduce: https://groups.google.com/g/reactivemongo/c/3Kb-tpAcO6Y
* Netty's docs: https://netty.io/4.0/api/io/netty/handler/timeout/IdleStateHandler.html

2021-05-11 19:45 UTC, cchantep commented on driver/src/main/scala/core/protocol/MongoHandler.scala
> -    last = System.nanoTime()
`last` would never be updated

2021-05-11 19:46 UTC, cchantep commented on driver/src/main/scala/core/protocol/MongoHandler.scala
> -import reactivemongo.io.netty.channel.{
Import reformating not acceptable

2021-05-12 06:44 UTC, jaceksokol commented on driver/src/main/scala/core/netty/ChannelFactory.scala
> +import java.util.concurrent.TimeUnit
Right, automatically performed by IDE, reverted.

2021-05-12 06:45 UTC, jaceksokol commented on driver/src/main/scala/core/protocol/MongoHandler.scala
> -    last = System.nanoTime()
Removed by mistake, reverted.

2021-05-12 06:45 UTC, jaceksokol commented on driver/src/main/scala/core/protocol/MongoHandler.scala
> -import reactivemongo.io.netty.channel.{
Reverted.

2021-05-12 08:16 UTC, cchantep requested changes

2021-05-12 08:16 UTC, cchantep commented on driver/src/main/scala/core/netty/ChannelFactory.scala
> +import java.util.concurrent.TimeUnit
Still not reverted, diff visible there

2021-05-12 08:16 UTC, cchantep commented on driver/src/main/scala/core/protocol/MongoHandler.scala
> +import java.util.concurrent.TimeUnit
Bad revert I guess

2021-05-12 08:41 UTC, jaceksokol commented on driver/src/main/scala/core/netty/ChannelFactory.scala
> +import java.util.concurrent.TimeUnit
This import is now required.

2021-05-12 08:45 UTC, jaceksokol commented on driver/src/main/scala/core/protocol/MongoHandler.scala
> +import java.util.concurrent.TimeUnit
Yes indeed.

2021-05-14 21:16 UTC, merged

2021-05-15 16:08 UTC, cchantep commented
Published in 1.0.4